cmake added to v2

diff --git a/bin/dinstall b/bin/dinstall
--- a/bin/dinstall
+++ b/bin/dinstall
@@ -1,6 +1,8 @@
 #!/bin/bash
 # Doug's installer
 
+set -e
+
 export TMPDIR=${TMPDIR:-/tmp/dndawso}
 export INSTALL_DIR=${INSTALL_DIR:-~/usr/local}
 cores=${cores:-8}
@@ -20,7 +22,29 @@ dostow () {
 }
 
 is_stowed () {
-    return test -d $INSTALL_DIR/stow/$1
+    test -d $INSTALL_DIR/stow/$1
+}
+
+is_installed () {
+    if [ ! -f $INSTALL_DIR/lib/dinstall/targets/${1}.sh ]; then
+        echo "Error: is_installed called on $1 which does not exist!"
+        return 1
+    fi
+    source $INSTALL_DIR/lib/dinstall/targets/${1}.sh
+    is_installed_$1
+}
+
+# use in dependencies_satisfied_xxx like:
+# require_packages name1 name2 name3 etc
+require_packages () {
+    while [[ $# > 0 ]]; do
+        if ! is_installed $1 ; then
+            echo "Package $1 is required! Install it first."
+            return 1
+        fi
+        shift
+    done
+    return 0
 }
 
 print_usage () {
@@ -33,6 +57,44 @@ print_usage () {
     echo -e "\tupdates palmetto scripts (and thus dinstall)"
 }
 
+
+# installs a package
+install () {
+    if [ ! -f $INSTALL_DIR/lib/dinstall/targets/${1}.sh ]; then
+        echo "Error: package $1 does not exist!"
+        return
+    fi
+    source $INSTALL_DIR/lib/dinstall/targets/${1}.sh
+
+    if is_installed_$1 ; then
+        echo "Error: package $1 is already installed!"
+        return
+    fi
+    if ! dependencies_satisfied_$1 ; then
+        echo "Error: dependencies not satisfied for $1!"
+        return
+    fi
+    install_$1
+}
+
+uninstall () {
+    if [ ! -f $INSTALL_DIR/lib/dinstall/targets/${1}.sh ]; then
+        echo "Error: package $1 does not exist!"
+        return
+    fi
+    source $INSTALL_DIR/lib/dinstall/targets/${1}.sh
+    if ! is_installed_$1 ; then
+        echo "Error: package $1 is not installed!"
+        return
+    fi
+    uninstall_$1
+}
+
+upgrade () {
+    uninstall $1
+    install $1
+}
+
 if [ "$#" -lt 1 ]; then
     echo "Not enough arguments!"
     print_usage
@@ -40,17 +102,42 @@ if [ "$#" -lt 1 ]; then
 fi
 
 if [ "$1" = "update" ]; then
-    if [ "$1" -ne 1 ]; then
+    if [ "$#" -ne 1 ]; then
         echo "Wrong arguments!"
         print_usage
         exit 1
     fi
-    cd $INSTALL_DIR/stow/palmetto_scripts
+    cd $INSTALL_DIR/stow/palmetto-scripts
     git pull
+    cd $INSTALL_DIR/stow
+    stow palmetto-scripts
+    exit 0
 fi
 
 
-exit 0
+
+
+case "$1" in
+    install|uninstall|upgrade)
+        cmd=$1
+        if [ $HOSTNAME = "user001" ]; then
+            echo "Warning! you are on user node!!"
+        fi
+
+        shift
+        while [[ $# > 0 ]]; do
+            $cmd $1
+            shift
+        done
+        exit 0
+        ;;
+esac
+
+
+echo "Error, unhandled command."
+print_usage
+exit 1
+
 
 
 export TMPDIR=${TMPDIR:-/tmp/dndawso}
